/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_abilix_robot_walktunner_Walk */

#ifndef _Included_com_abilix_robot_walktunner_Walk
#define _Included_com_abilix_robot_walktunner_Walk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_abilix_robot_walktunner_Walk
 * Method:    startWalk
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_abilix_robot_walktunner_Walk_initWalk
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_abilix_robot_walktunner_Walk_startForwardWalk
  (JNIEnv * env, jobject obj,jint speed);

JNIEXPORT void JNICALL Java_com_abilix_robot_walktunner_Walk_startBackwardWalk
  (JNIEnv * env, jobject obj,jint speed);

JNIEXPORT void JNICALL Java_com_abilix_robot_walktunner_Walk_startLeftWalk
  (JNIEnv * env, jobject obj,jint speed);

JNIEXPORT void JNICALL Java_com_abilix_robot_walktunner_Walk_startRightWalk
  (JNIEnv * env, jobject obj,jint speed);

JNIEXPORT void JNICALL Java_com_abilix_robot_walktunner_Walk_startLeftForwardWalk
  (JNIEnv * env, jobject obj,jint leftSpeed,jint forwardSpeed);

JNIEXPORT void JNICALL Java_com_abilix_robot_walktunner_Walk_startLeftBackwardWalk
  (JNIEnv * env, jobject obj,jint leftSpeed,jint backwardSpeed);

JNIEXPORT void JNICALL Java_com_abilix_robot_walktunner_Walk_startRightForwardWalk
  (JNIEnv * env, jobject obj,jint rightSpeed,jint forwardSpeed);

JNIEXPORT void JNICALL Java_com_abilix_robot_walktunner_Walk_startRightBackwardWalk
  (JNIEnv * env, jobject obj,jint rightSpeed,jint backwardSpeed);

JNIEXPORT void JNICALL Java_com_abilix_robot_walktunner_Walk_startTurnWalk
  (JNIEnv * env, jobject obj,jint speed,jint direction,jint flag);

/*
 * Class:     com_abilix_robot_walktunner_Walk
 * Method:    stopwalk
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_abilix_robot_walktunner_Walk_stopwalk
  (JNIEnv *, jobject);


JNIEXPORT void Java_com_abilix_robot_walktunner_Walk_updateGyro
  (JNIEnv * env , jobject obj,jfloat x,jfloat y,jfloat z);

JNIEXPORT void Java_com_abilix_robot_walktunner_Walk_updateAccele
  (JNIEnv * env , jobject obj,jfloat x,jfloat y,jfloat z);

JNIEXPORT void Java_com_abilix_robot_walktunner_Walk_updateAngle
  (JNIEnv * env , jobject obj,jfloat pitch,jfloat roll,jfloat yaw);
/*
 * Class:     com_abilix_robot_walktunner_Walk
 * Method:    getMotorValue
 * Signature: ()[B
 */
JNIEXPORT jintArray JNICALL Java_com_abilix_robot_walktunner_Walk_getMotorValue
  (JNIEnv *, jobject);

extern float gyro_x, gyro_y, accel_x, accel_y;
extern float pose_roll, pose_pitch, pose_yaw;

#ifdef __cplusplus
}
#endif
#endif
